### Crear estudiante
POST http://localhost:8000/users/student
Accept: application/json
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Perez",
  "fecha_nacimiento": "1990-01-01",
  "genero": "M",
  "usuario": "juanperez",
  "password": "123456",
  "carnet": "21654",
  "correo": "jperz@gmail.com",
  "parqueo": false,
  "foranteo": false,
  "colegio": "Colegio de San Francisco"
}

### Crear profesor
POST http://localhost:8000/users/teacher
Accept: application/json
Content-Type: application/json

{
  "nombre": "John",
  "apellido": "Doe",
  "fecha_nacimiento": "1990-01-01",
  "genero": "M",
  "usuario": "JDOE",
  "password": "123456",
  "code": "19999",
  "correo": "jdoe@uvg.edu.gt",
  "departamento": "Departamento de Matematicas",
  "maestria": "Matematicas",
  "jornada": "Matutina"
}

### Obtener carreras
GET http://localhost:8000/careers
Accept: application/json

### Obtener signos
GET http://localhost:8000/signs
Accept: application/json

### Obtener equipos
GET http://localhost:8000/teams

### Obtener canciones
GET http://localhost:8000/songs

### Crear relación Persona - ES_Signo -> Signo
POST http://localhost:8000/signs/is
Accept: application/json
Content-Type: application/json

{
  "signo": "Aries",
  "usuario": "juanperez",
  "compatibilidad": 5,
  "influencia": true,
  "compartir": true
}

### Crear relación Persona - ESTUDIA - Carrera
POST http://localhost:8000/careers/studies
Accept: application/json
Content-Type: application/json

{
  "carrera": "Ciencias de la computación y tecnologías de la información",
  "usuario": "juanperez",
  "apasiona": true,
  "activo": true,
  "year": 1
}
