GET http://localhost:8080/users/careers
Accept: application/json

###
POST http://localhost:8080/users/student
Accept: application/json
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Perez",
  "fecha_nacimiento": "1990-01-01",
  "genero": "M",
  "usuario": "juanperez",
  "password": "123456",
  "carnet": "21654",
  "correo": "jperz@gmail.com",
  "parqueo": false,
  "foranteo": false,
  "colegio": "Colegio de San Francisco"
}

###

