### Crear estudiante
POST http://localhost:8080/users/student
Accept: application/json
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Perez",
  "fecha_nacimiento": "1990-01-01",
  "genero": "M",
  "usuario": "juanperez",
  "password": "123456",
  "carnet": "21654",
  "correo": "jperz@gmail.com",
  "colegio": "Colegio de San Francisco",
  "foraneo": false,
  "parqueo": false
}

### Crear estudiante
POST http://localhost:8080/users/student
Accept: application/json
Content-Type: application/json

{
"nombre": "Jimena",
"apellido": "Henández",
"fecha_nacimiento": "2004-01-10",
"genero": "Femenino",
"usuario": "koji",
"password": "nutella21",
"carnet": "21199",
"correo": "her21199@uvg.edu.gt",
"parqueo": true,
"foraneo": true,
"colegio": "Boston"
}

### Crear profesor
POST http://localhost:8080/users/teacher
Accept: application/json
Content-Type: application/json

{
  "nombre": "John",
  "apellido": "Doe",
  "fecha_nacimiento": "1990-01-01",
  "genero": "M",
  "usuario": "JDOE",
  "password": "123456",
  "code": "19999",
  "correo_profesor": "jdoe@uvg.edu.gt",
  "departamento": "Departamento de Matematicas",
  "maestria": "Matematicas",
  "jornada": "Matutina"
}

### Crear Profesor que también es Estudiante
POST http://localhost:8080/users/teacher-student
Accept: application/json
Content-Type: application/json

{
  "nombre": "Javier",
  "apellido": "Perez",
  "fecha_nacimiento": "1990-01-01",
  "genero": "M",
  "usuario": "javierperez",
  "password": "123456",
  "carnet": "21654",
  "correo": "jperz@gmail.com",
  "parqueo": false,
  "foraneo": true,
  "colegio": "Colegio de San Francisco",
  "code": "19562",
  "correo_profesor": "jper@uvg.edu.gt",
  "departamento": "Departamento de Matematicas",
  "maestria": "Matematicas",
  "jornada": "Matutina"
}

### Obtener carreras
GET http://localhost:8080/careers
Accept: application/json

### Obtener signos
GET http://localhost:8080/signs
Accept: application/json

### Obtener equipos
GET http://localhost:8080/teams

### Obtener canciones
GET http://localhost:8080/songs

### Crear Cancion
POST http://localhost:8080/songs
Accept: application/json
Content-Type: application/json

{
  "nombre": "Rap God",
  "disco": "The Marshall Mathers LP 2",
  "fecha_lanzamiento": "2013-10-15",
  "genero": "Rap",
  "duracion": 6.03
}

### Crear relación Persona - ES_Signo -> Signo
POST http://localhost:8080/signs/is
Accept: application/json
Content-Type: application/json

{
  "signo": "Aries",
  "usuario": "juanperez",
  "compatibilidad": 5,
  "influencia": true,
  "compartir": true
}

### Crear relación Persona - ESTUDIA - Carrera
POST http://localhost:8080/careers/studies
Accept: application/json
Content-Type: application/json

{
  "carrera": "Ciencias de la computación y tecnologías de la información",
  "usuario": "juanperez",
  "apasiona": true,
  "activo": true,
  "year": 1
}

### Crear relación Persona - INTERESA - Carrera
POST http://localhost:8080/careers/interests
Accept: application/json
Content-Type: application/json

{
  "carrera": "Ciencias de la computación y tecnologías de la información",
  "usuario": "juanperez",
  "intereses": [
    "Desarrollo de software"
  ],
  "recomendado": true,
  "estudiara": true
}

### Crear relación Persona - VISITÓ - Lugar
POST http://localhost:8080/places/visited
Accept: application/json
Content-Type: application/json

{
  "usuario": "juanperez",
  "lugar": "Lago de Atitlán",
  "cuando": "2021-01-01",
  "rating": 5,
  "categoria": "Naturaleza"
}

### Crear relación Persona - FAVORITA - Canción
POST http://localhost:8080/songs/favorite
Accept: application/json
Content-Type: application/json

{
  "usuario": "juanperez",
  "cancion": "Bohemian Rhapsody",
  "cuando": "2021-02-02",
  "como": "En una película",
  "frecuencia": "Diaria"
}

### Crear relación Persona - GUSTA - Canción
POST http://localhost:8080/songs/likes
Accept: application/json
Content-Type: application/json

{
  "usuario": "juanperez",
  "cancion": "Shape of You",
  "como": "En una película",
  "escucha": true,
  "mas_artista": true
}

### Crear relación Persona - NO_GUSTA - Canción
POST http://localhost:8080/songs/dislikes
Accept: application/json
Content-Type: application/json

{
  "usuario": "juanperez",
  "cancion": "Hotel California",
  "motivo": "No me gusta la letra",
  "cambiar": false,
  "intensidad": 4
}

### Crear relación Persona - APOYA - Equipo
POST http://localhost:8080/teams/likes
Accept: application/json
Content-Type: application/json

{
  "usuario": "juanperez",
  "equipo": "Los Angeles Lakers",
  "fecha": "2021-03-03",
  "por_que": "Porque es el mejor equipo del mundo",
  "mira_partidos": true
}

### Crear relación Persona - NO_APOYA - Equipo
POST http://localhost:8080/teams/dislikes
Accept: application/json
Content-Type: application/json

{
  "usuario": "juanperez",
  "equipo": "Real Madrid",
  "fecha": "2021-03-03",
  "por_que": "Porque es el peor equipo del mundo",
  "mira_partidos": false
}

### Obtener detalles de cuenta
GET http://localhost:8080/users/details/juanperez
Accept: application/json

### Iniciar sesión
POST http://localhost:8080/users/login
Accept: application/json
Content-Type: application/json

{
  "usuario": "juanperez",
  "password": "123456"
}

### Añadir publicación
POST http://localhost:8080/users/post
Accept: application/json
Content-Type: application/json

{
  "usuario": "juanperez",
  "contenido": "Hola, soy Juan Perez 2"
}

### Clear posts
DELETE http://localhost:8080/users/clear/juanperez
Accept: application/json

### Añadir 'me recuerda a' a canción favorita
PUT http://localhost:8080/songs/remembers
Accept: application/json
Content-Type: application/json

{
  "usuario": "juanperez",
  "cancion": "Bohemian Rhapsody",
  "me_recuerda_a": "Mi infancia"
}

### eliminar 'me recuerda a' a canción favorita
POST http://localhost:8080/songs/remembers/remove
Accept: application/json
Content-Type: application/json

{
  "usuario": "juanperez",
  "cancion": "Bohemian Rhapsody"
}

### Añadir prefered music player
PUT http://localhost:8080/songs/music-player
Accept: application/json
Content-Type: application/json

{
  "usuario": "juanperez",
  "music_player": "Spotify"
}

### remove prefered music player
DELETE http://localhost:8080/songs/music-player/juanperez
Accept: application/json

### Admin tag users
POST http://localhost:8080/admin/tag
Accept: application/json
Content-Type: application/json

{
  "users": ["koji", "juanperez"],
  "tag": "Premium",
  "value": true
}

### Admin remove tag from user
POST http://localhost:8080/admin/tag/remove
Accept: application/json
Content-Type: application/json

{
    "users": ["koji"],
    "tag": "Premium"
}

### Admin Get all users
GET http://localhost:8080/admin/users?filter=Premium
Accept: application/json

### Admin Delete multiple users
POST http://localhost:8080/admin/users/delete
Accept: application/json
Content-Type: application/json

{
    "users": ["juanperezz", "juanperezzz"]
}

### Admin metrics
GET http://localhost:8080/admin/metrics
Accept: application/json

